### ISSUE TITLE
Changing MAC Address

### ISSUE THREAD

**Issue by CingularJYC** [R-YaTian/TinkeDSi#10]
Hello. I would like to change MAC Address on DSi firmware without breaking DS Communications. Is there any way to get it fixed? I tried it, but Connection 1, 2, & 3, and DS Communications do not work anymore.

**Comment by CingularJYC** [comment]
I finally figured out with https://problemkaputt.de/gbatek-ds-firmware-wifi-calibration-data.htm!

**Comment by R-YaTian** [comment]
> I finally figured out with https://problemkaputt.de/gbatek-ds-firmware-wifi-calibration-data.htm!

Nice! And I think this is not a TinkeDSi issue actually. :p

**Comment by CingularJYC** [comment]
Oh! My fault!
