### ISSUE TITLE
[Bug] ROM export gives Index OoB error when overlay is changed

### ISSUE THREAD

**Issue by SilverstarStream** [R-YaTian/TinkeDSi#2]
I'm editing Pokemon White 2. After swapping out overlay 35 with an edited version then trying to save the ROM, Tinke gives the following error:
![tinke issue](https://user-images.githubusercontent.com/46911095/174518412-d0f1533b-6bcb-4751-a12c-64a52ab38abb.png)

I double-checked the ROM's checksum and it is clean. The only files I am changing are overlay 35 and y9.bin (overlay table, edited to mark the overlay as uncompressed). The overlay was decompressed after extraction from Tinke with blz from these tools: https://gbatemp.net/download/nintendo-ds-gba-compressors-by-cue.37133/
However, this error still occurs even if I only edit a byte in the compressed overlay and try to reinsert it, changing nothing else.

Please let me know if there's any other context or information I can provide.

**Comment by R-YaTian** [comment]
Please upload your overlay 35 and y9.bin files for testing purpose. I will look into it in my free time.

**Comment by SilverstarStream** [comment]
Here you go. Thanks for looking into this.
[White2_Overlay_Upload.zip](https://github.com/R-YaTian/TinkeDSi/files/9175046/White2_Overlay_Upload.zip)

**Comment by R-YaTian** [comment]
It's ARM9BLZ decompress issue, I fixed it now. Please try this [debug build](https://github.com/R-YaTian/TinkeDSi/suites/8084374704/artifacts/348822829).

**Comment by SilverstarStream** [comment]
I was able to edit the ROM with this build, thank you so much for fixing it. The edits work on both emulator and hardware, which is great. Sorry I took a while to get around to trying this.

**Comment by dj5927** [comment]
> It's ARM9BLZ decompress issue, I fixed it now. Please try this [debug build](https://github.com/R-YaTian/TinkeDSi/suites/8084374704/artifacts/348822829).

I’m having the same problem.
I attempted to download the debug version, but the link is no longer working.
I would greatly appreciate your assistance.

**Comment by R-YaTian** [comment]
> > It's ARM9BLZ decompress issue, I fixed it now. Please try this [debug build](https://github.com/R-YaTian/TinkeDSi/suites/8084374704/artifacts/348822829).
> 
> I’m having the same problem. I attempted to download the debug version, but the link is no longer working. I would greatly appreciate your assistance.

Download latest nightly build here: https://github.com/R-YaTian/TinkeDSi/actions/runs/22572800397

**Comment by dj5927** [comment]
> > > It's ARM9BLZ decompress issue, I fixed it now. Please try this [debug build](https://github.com/R-YaTian/TinkeDSi/suites/8084374704/artifacts/348822829).
> > 
> > 
> > I’m having the same problem. I attempted to download the debug version, but the link is no longer working. I would greatly appreciate your assistance.
> 
> Download latest nightly build here: https://github.com/R-YaTian/TinkeDSi/actions/runs/22572800397


Could you please take a look at this file? An error occurs even when using the nightly build. The issue strictly happens when the overlay file is inserted. Please note that this file was modified for Korean localization purposes.

[ftc.zip](https://github.com/user-attachments/files/25699814/ftc.zip)

**Comment by R-YaTian** [comment]
> > > > It's ARM9BLZ decompress issue, I fixed it now. Please try this [debug build](https://github.com/R-YaTian/TinkeDSi/suites/8084374704/artifacts/348822829).
> > > 
> > > 
> > > I’m having the same problem. I attempted to download the debug version, but the link is no longer working. I would greatly appreciate your assistance.
> > 
> > 
> > Download latest nightly build here: https://github.com/R-YaTian/TinkeDSi/actions/runs/22572800397
> 
> Could you please take a look at this file? An error occurs even when using the nightly build. The issue strictly happens when the overlay file is inserted. Please note that this file was modified for Korean localization purposes.
> 
> [ftc.zip](https://github.com/user-attachments/files/25699814/ftc.zip)

Try https://github.com/R-YaTian/TinkeDSi/actions/runs/22607137428 which fix this issue.

**Comment by dj5927** [comment]
> > > > > It's ARM9BLZ decompress issue, I fixed it now. Please try this [debug build](https://github.com/R-YaTian/TinkeDSi/suites/8084374704/artifacts/348822829).
> > > > 
> > > > 
> > > > I’m having the same problem. I attempted to download the debug version, but the link is no longer working. I would greatly appreciate your assistance.
> > > 
> > > 
> > > Download latest nightly build here: https://github.com/R-YaTian/TinkeDSi/actions/runs/22572800397
> > 
> > 
> > Could you please take a look at this file? An error occurs even when using the nightly build. The issue strictly happens when the overlay file is inserted. Please note that this file was modified for Korean localization purposes.
> > [ftc.zip](https://github.com/user-attachments/files/25699814/ftc.zip)
> 
> Try https://github.com/R-YaTian/TinkeDSi/actions/runs/22607137428 which fix this issue.



Thank you. It is now working properly. I truly appreciate your support.
