### ISSUE TITLE
Translation help

### ISSUE THREAD

**Issue by Ega1232387** [R-YaTian/TinkeDSi#4]
Hello!
Could I help you with translating TinkeDSi to Russian?

**Comment by R-YaTian** [comment]
> Hello! Could I help you with translating TinkeDSi to Russian?

Hi, a new target language Russian have been added to [Crowdin](https://crwd.in/tinkedsi) project now, you can do translate here.
After you finish it, I will add Russian support for TinkeDSi. Sorry for my late reply :p

**Comment by Ega1232387** [comment]
Nice, thanks!
